package com.blossom.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import com.blossom.repository.CarRepository;
import com.blossom.model.Car;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class CarController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private CarRepository carRepository;

	@PostMapping(path="/add")
	@ResponseStatus(HttpStatus.CREATED)
	@ResponseBody
	public String addNewCar (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Car n = new Car();
		n.setName(name);
		carRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	@ResponseBody
	public Iterable<Car> getAllCars() {
		// This returns a JSON or XML with the users
		return carRepository.findAll();
	}
}
